#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

# sudo not required for some system commands
for command in mount umount sv pacman updatedb su shutdown poweroff reboot ; do
	alias $command="sudo $command"
done; unset command

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	bc="bc -ql" \
	mkd="mkdir -pv" \
	yt="youtube-dl --add-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner" \
	cls="clear" \
	n="nnn" \

# Colorize commands when possible.
alias \
	ls="lsd" \
	lsa="lsd -a" \
	lsl="lsd -l" \
	lsla="lsd -la" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi"

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall -9" \
	cat="bat" \
	g="git" \
	trem="transmission-remote" \
	YT="youtube-viewer" \
	sdn="shutdown -h now" \
	e="$EDITOR" \
	v="$EDITOR" \
	p="pacman" \
	xi="sudo xbps-install" \
	xr="sudo xbps-remove -R" \
	xq="xbps-query" \
	z="zathura" \
	rb="reboot" \
	pipes="pipes.sh" \
	sx="sxiv" \
	xmc="nvim ~/.xmonad/xmonad.hs" \
	xmb1="nvim ~/.config/xmobar/xmobarrc1" \
	xmb0="nvim ~/.config/xmobar/xmobarrc0"

alias \
	magit="nvim -c MagitOnly" \
	ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/zshnameddirrc" \
	weath="less -S ${XDG_DATA_HOME:-$HOME/.local/share}/weatherreport" \

cwm(){ du -ax ~/.local/src/dwm | awk '{ print $2 }' | fzf | xargs -r nvim }
ecf(){ du -ax ~/.dotfiles/home/.config/ | awk '{ print $2 }' | fzf | xargs -r nvim }
esc(){ du -ax ~/.dotfiles/home/.local/bin/ | awk '{ print $2 }' | fzf | xargs -r nvim }
